import type { Course } from "@/lib/types"

export type StaticLmsCourse = Omit<Course, "createdAt" | "updatedAt"> & {
  createdAt: string | Date
  updatedAt: string | Date
}

// Generated by `pnpm lms:export-courses`.
// Keep this array in git so public LMS catalog/course metadata can be served
// without spending Firestore reads on every visitor, build, or page refresh.
export const STATIC_LMS_COURSE_DATA: StaticLmsCourse[] = []

function hydrateCourse(course: StaticLmsCourse): Course {
  return {
    ...course,
    createdAt: course.createdAt instanceof Date ? course.createdAt : new Date(course.createdAt),
    updatedAt: course.updatedAt instanceof Date ? course.updatedAt : new Date(course.updatedAt),
  }
}

export function getStaticLmsCourses(): Course[] {
  return STATIC_LMS_COURSE_DATA.map(hydrateCourse).sort((a, b) => {
    const category = a.category.localeCompare(b.category)
    return category !== 0 ? category : a.title.localeCompare(b.title)
  })
}

export function getStaticLmsCourseBySlug(slug: string): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.slug === slug)
  return course ? hydrateCourse(course) : null
}

export function getStaticLmsCourseById(id: number): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.id === id)
  return course ? hydrateCourse(course) : null
}
