import { getSessionUser } from "@/app/actions/auth"
import { isSuperAdmin as checkIsSuperAdmin } from "@/lib/access-control"
import { adminDb } from "@/lib/firebase-admin"
import { exec } from "child_process"
import { promisify } from "util"
import fs from "fs/promises"
import path from "path"
import type { Course } from "@/lib/types"

const execAsync = promisify(exec)

export async function POST(req: Request) {
  // Authorization check
  const user = await getSessionUser()
  if (!user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 })
  }

  const isSuperAdmin = checkIsSuperAdmin(user)
  if (!isSuperAdmin && user.role !== "admin" && user.role !== "super_admin" && user.role !== "group_head" && user.role !== "lead") {
    return new Response(JSON.stringify({ error: "Forbidden: Admin access required" }), { status: 403 })
  }

  const encoder = new TextEncoder()
  const stream = new ReadableStream({
    async start(controller) {
      function log(msg: string) {
        controller.enqueue(encoder.encode(JSON.stringify({ log: msg }) + "\n"))
      }

      try {
        const currentCwd = process.cwd()
        const realCwd = currentCwd.includes("standalone") 
          ? path.join(currentCwd, "..", "..") 
          : currentCwd
          
        log("Fetching courses from Firestore...")
        const snapshot = await adminDb.collection("courses").get()
        const courses = snapshot.docs.map(doc => doc.data() as Course)
        
        log(`Fetched ${courses.length} courses. Processing data...`)
        
        // Convert to static format
        const staticData = courses.map(c => ({
          ...c,
          createdAt: c.createdAt instanceof Date ? c.createdAt.toISOString() : 
                     (c.createdAt as any)?.toDate ? (c.createdAt as any).toDate().toISOString() : 
                     new Date().toISOString(),
          updatedAt: c.updatedAt instanceof Date ? c.updatedAt.toISOString() : 
                     (c.updatedAt as any)?.toDate ? (c.updatedAt as any).toDate().toISOString() : 
                     new Date().toISOString(),
        }))

        staticData.sort((a, b) => {
          const catA = a.category || ""
          const catB = b.category || ""
          const titleA = a.title || ""
          const titleB = b.title || ""
          const cat = catA.localeCompare(catB)
          return cat !== 0 ? cat : titleA.localeCompare(titleB)
        })

        const fileContent = `import type { Course } from "@/lib/types"

export type StaticLmsCourse = Omit<Course, "createdAt" | "updatedAt"> & {
  createdAt: string | Date
  updatedAt: string | Date
}

// Generated by Hybrid Sync
export const STATIC_LMS_COURSE_DATA: StaticLmsCourse[] = ${JSON.stringify(staticData, null, 2)}

function hydrateCourse(course: StaticLmsCourse): Course {
  return {
    ...course,
    createdAt: course.createdAt instanceof Date ? course.createdAt : new Date(course.createdAt),
    updatedAt: course.updatedAt instanceof Date ? course.updatedAt : new Date(course.updatedAt),
  }
}

export function getStaticLmsCourses(): Course[] {
  return STATIC_LMS_COURSE_DATA.map(hydrateCourse).sort((a, b) => {
    const catA = a.category || ""
    const catB = b.category || ""
    const titleA = a.title || ""
    const titleB = b.title || ""
    const category = catA.localeCompare(catB)
    return category !== 0 ? category : titleA.localeCompare(titleB)
  })
}

export function hasStaticLmsCourses(): boolean {
  return STATIC_LMS_COURSE_DATA.length > 0
}

export function getStaticLmsCourseBySlug(slug: string): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.slug === slug)
  return course ? hydrateCourse(course) : null
}

export function getStaticLmsCourseById(id: number): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.id === id)
  return course ? hydrateCourse(course) : null
}
`
        let pushedToGithub = false
        const githubToken = process.env.GITHUB_TOKEN
        const repoPath = process.env.GITHUB_REPO || "QuisTech/eib-stratoc-q2-2026-performance"
        const filePathTarget = "lib/static-lms-courses.ts"

        if (githubToken) {
          log("Proceeding with GitHub API integration...")
          
          log("Fetching current file SHA from GitHub...")
          const getRes = await fetch(`https://api.github.com/repos/${repoPath}/contents/${filePathTarget}`, {
            headers: {
              Authorization: `Bearer ${githubToken}`,
              "X-GitHub-Api-Version": "2022-11-28",
              "User-Agent": "LMS-Hybrid-Sync"
            }
          })
          
          let sha = ""
          if (getRes.ok) {
            const getData = await getRes.json()
            sha = getData.sha
          } else if (getRes.status !== 404) {
            log(`Failed to fetch from GitHub: ${getRes.status} ${await getRes.text()}`)
          }

          if (getRes.ok || getRes.status === 404) {
            log("Pushing updated file directly to GitHub...")
            const putRes = await fetch(`https://api.github.com/repos/${repoPath}/contents/${filePathTarget}`, {
              method: "PUT",
              headers: {
                Authorization: `Bearer ${githubToken}`,
                "X-GitHub-Api-Version": "2022-11-28",
                "Content-Type": "application/json",
                "User-Agent": "LMS-Hybrid-Sync"
              },
              body: JSON.stringify({
                message: "chore: hybrid sync - update static courses catalog",
                content: Buffer.from(fileContent).toString("base64"),
                ...(sha ? { sha } : {})
              })
            })

            if (!putRes.ok) {
              log(`GitHub push failed: ${putRes.status} ${await putRes.text()}`)
            } else {
              log("Successfully pushed to GitHub! Remote deployments will trigger automatically.")
              pushedToGithub = true
            }
          }
        } else {
          log("No GITHUB_TOKEN found. Skipping GitHub push.")
        }

        const isVercel = process.env.VERCEL === "1"
        if (isVercel) {
          log("Vercel environment detected. Sync complete.")
          controller.close()
          return
        }

        // --- ON-PREMISE (LOCAL) MODE ---
        log("Writing new static-lms-courses.ts file...")
        const filePath = path.join(realCwd, "lib", "static-lms-courses.ts")
        await fs.writeFile(filePath, fileContent)

        log("Staging changes in git (git add)...")
        try {
          await execAsync("git add public/uploads", { cwd: realCwd })
        } catch (e) {
          // ignore if directory doesn't exist
        }

        log("Committing changes...")
        try {
          await execAsync('git commit -am "chore: hybrid sync - update courses and media"', { cwd: realCwd })
        } catch (e: any) {
          log("No new changes detected to commit, or commit failed. Continuing...")
        }

        log("Pushing to GitHub (origin main)...")
        try {
          const pushResult = await execAsync("git push origin main", { cwd: realCwd })
          log(pushResult.stdout || pushResult.stderr || "Push successful.")
        } catch (pushErr: any) {
          log("Warning: Could not push to GitHub (VPS lacks credentials). Vercel deploy skipped, continuing with local VPS update...")
        }

        log("Building Next.js application (this may take a minute)...")
        try {
          const cleanEnv = { ...process.env }
          for (const key of Object.keys(cleanEnv)) {
            if (key.startsWith('__NEXT_') || key === 'NEXT_PHASE' || key === 'NODE_OPTIONS') {
              delete cleanEnv[key]
            }
          }
          const buildCommand = `npx next build && node scripts/postbuild.js`
          const buildResult = await execAsync(buildCommand, { 
            env: cleanEnv as any,
            cwd: realCwd 
          })
          log("Build completed successfully!")
        } catch (buildErr: any) {
          log("Build failed! " + (buildErr.stderr || buildErr.message))
          throw new Error("Build failed")
        }

        log("Restarting PM2 server... The dashboard will refresh automatically when it's back online.")
        
        // We close the stream here so the client gets the final message
        controller.close()

        // Give the stream 2 seconds to flush to the client before killing the server
        setTimeout(() => {
          exec("pm2 restart ecosystem.config.js --env production", { cwd: realCwd }, (error) => {
            if (error) console.error("PM2 Restart Failed:", error)
          })
        }, 2000)

      } catch (error: any) {
        console.error("Hybrid Sync Error:", error)
        controller.enqueue(encoder.encode(JSON.stringify({ error: error.message || "Unknown error" }) + "\n"))
        controller.close()
      }
    }
  })

  return new Response(stream, {
    headers: {
      "Content-Type": "application/json",
      "Transfer-Encoding": "chunked"
    }
  })
}
