import { getSessionUser } from "@/app/actions/auth"
import { isSuperAdminEmail } from "@/lib/access-control"
import { adminDb } from "@/lib/firebase-admin"
import { exec } from "child_process"
import { promisify } from "util"
import fs from "fs/promises"
import path from "path"
import type { Course } from "@/lib/types"

const execAsync = promisify(exec)

export async function POST(req: Request) {
  // Authorization check
  const user = await getSessionUser()
  if (!user) {
    return new Response(JSON.stringify({ error: "Unauthorized" }), { status: 401 })
  }

  const isSuperAdmin = isSuperAdminEmail(user.email)
  if (!isSuperAdmin && user.role !== "admin" && user.role !== "super_admin" && user.role !== "group_head" && user.role !== "lead") {
    return new Response(JSON.stringify({ error: "Forbidden: Admin access required" }), { status: 403 })
  }

  const encoder = new TextEncoder()
  const stream = new ReadableStream({
    async start(controller) {
      function log(msg: string) {
        controller.enqueue(encoder.encode(JSON.stringify({ log: msg }) + "\n"))
      }

      try {
        log("Fetching courses from Firestore...")
        const snapshot = await adminDb.collection("courses").get()
        const courses = snapshot.docs.map(doc => doc.data() as Course)
        
        log(`Fetched ${courses.length} courses. Processing data...`)
        
        // Convert to static format
        const staticData = courses.map(c => ({
          ...c,
          createdAt: c.createdAt instanceof Date ? c.createdAt.toISOString() : 
                     (c.createdAt as any)?.toDate ? (c.createdAt as any).toDate().toISOString() : 
                     new Date().toISOString(),
          updatedAt: c.updatedAt instanceof Date ? c.updatedAt.toISOString() : 
                     (c.updatedAt as any)?.toDate ? (c.updatedAt as any).toDate().toISOString() : 
                     new Date().toISOString(),
        }))

        staticData.sort((a, b) => {
          const cat = a.category.localeCompare(b.category)
          return cat !== 0 ? cat : a.title.localeCompare(b.title)
        })

        const fileContent = `import type { Course } from "@/lib/types"

export type StaticLmsCourse = Omit<Course, "createdAt" | "updatedAt"> & {
  createdAt: string | Date
  updatedAt: string | Date
}

// Generated by Hybrid Sync
export const STATIC_LMS_COURSE_DATA: StaticLmsCourse[] = ${JSON.stringify(staticData, null, 2)}

function hydrateCourse(course: StaticLmsCourse): Course {
  return {
    ...course,
    createdAt: course.createdAt instanceof Date ? course.createdAt : new Date(course.createdAt),
    updatedAt: course.updatedAt instanceof Date ? course.updatedAt : new Date(course.updatedAt),
  }
}

export function getStaticLmsCourses(): Course[] {
  return STATIC_LMS_COURSE_DATA.map(hydrateCourse).sort((a, b) => {
    const category = a.category.localeCompare(b.category)
    return category !== 0 ? category : a.title.localeCompare(b.title)
  })
}

export function hasStaticLmsCourses(): boolean {
  return STATIC_LMS_COURSE_DATA.length > 0
}

export function getStaticLmsCourseBySlug(slug: string): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.slug === slug)
  return course ? hydrateCourse(course) : null
}

export function getStaticLmsCourseById(id: number): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.id === id)
  return course ? hydrateCourse(course) : null
}
`
        log("Writing new static-lms-courses.ts file...")
        const filePath = path.join(process.cwd(), "lib", "static-lms-courses.ts")
        await fs.writeFile(filePath, fileContent)

        log("Staging changes in git (git add)...")
        try {
          await execAsync("git add public/uploads")
        } catch (e) {
          // ignore if directory doesn't exist
        }

        log("Committing changes...")
        try {
          await execAsync('git commit -am "chore: hybrid sync - update courses and media"')
        } catch (e: any) {
          log("No new changes detected to commit, or commit failed. Continuing...")
        }

        log("Pushing to GitHub (origin main)...")
        try {
          const pushResult = await execAsync("git push origin main")
          log(pushResult.stdout || pushResult.stderr || "Push successful.")
        } catch (pushErr: any) {
          log("Warning: Could not push to GitHub (VPS lacks credentials). Vercel deploy skipped, continuing with local VPS update...")
        }

        log("Building Next.js application (this may take a minute)...")
        try {
          const cleanEnv = { ...process.env }
          for (const key of Object.keys(cleanEnv)) {
            if (key.startsWith('__NEXT_') || key === 'NEXT_PHASE' || key === 'NODE_OPTIONS') {
              delete cleanEnv[key]
            }
          }
          const buildCommand = `node node_modules/next/dist/bin/next build "${process.cwd()}" && node scripts/postbuild.js`
          const buildResult = await execAsync(buildCommand, { 
            env: cleanEnv as any,
            cwd: process.cwd() 
          })
          log("Build completed successfully!")
        } catch (buildErr: any) {
          log("Build failed! " + (buildErr.stderr || buildErr.message))
          throw new Error("Build failed")
        }

        log("Restarting PM2 server... The dashboard will refresh automatically when it's back online.")
        
        // We close the stream here so the client gets the final message
        controller.close()

        // Give the stream 2 seconds to flush to the client before killing the server
        setTimeout(() => {
          exec("pm2 restart ecosystem.config.js --env production", (error) => {
            if (error) console.error("PM2 Restart Failed:", error)
          })
        }, 2000)

      } catch (error: any) {
        console.error("Hybrid Sync Error:", error)
        controller.enqueue(encoder.encode(JSON.stringify({ error: error.message || "Unknown error" }) + "\n"))
        controller.close()
      }
    }
  })

  return new Response(stream, {
    headers: {
      "Content-Type": "application/json",
      "Transfer-Encoding": "chunked"
    }
  })
}
