import fs from 'fs';
import path from 'path';
import { STATIC_LMS_COURSE_DATA } from '../lib/static-lms-courses';

const slug = 'advanced-digital-intelligence-operations-manual';
const coverUrl = 'https://cdn.jsdelivr.net/gh/QuisTech/eib-lms-images@main/advanced-digital-intelligence-operations-manual/course_cover.png';

function updateStaticCourses() {
  const filePath = path.resolve(__dirname, '../lib/static-lms-courses.ts');
  
  const courseIndex = STATIC_LMS_COURSE_DATA.findIndex(c => c.slug === slug);
  if (courseIndex === -1) throw new Error("Course not found");

  const course = STATIC_LMS_COURSE_DATA[courseIndex];
  
  // Set the imageUrl for the course itself
  course.imageUrl = coverUrl;

  // Re-generate the entire file
  const fileContent = `import type { Course } from "@/lib/types"

export type StaticLmsCourse = Omit<Course, "createdAt" | "updatedAt"> & {
  createdAt: string | Date
  updatedAt: string | Date
}

// Generated by Hybrid Sync
export const STATIC_LMS_COURSE_DATA: StaticLmsCourse[] = ${JSON.stringify(STATIC_LMS_COURSE_DATA, null, 2)}

function hydrateCourse(course: StaticLmsCourse): Course {
  return {
    ...course,
    createdAt: course.createdAt instanceof Date ? course.createdAt : new Date(course.createdAt),
    updatedAt: course.updatedAt instanceof Date ? course.updatedAt : new Date(course.updatedAt),
  }
}

export function getStaticLmsCourses(): Course[] {
  return STATIC_LMS_COURSE_DATA.map(hydrateCourse).sort((a, b) => {
    const category = a.category.localeCompare(b.category)
    return category !== 0 ? category : a.title.localeCompare(b.title)
  })
}

export function hasStaticLmsCourses(): boolean {
  return STATIC_LMS_COURSE_DATA.length > 0
}

export function getStaticLmsCourseBySlug(slug: string): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.slug === slug)
  return course ? hydrateCourse(course) : null
}

export function getStaticLmsCourseById(id: number): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.id === id)
  return course ? hydrateCourse(course) : null
}
`;

  fs.writeFileSync(filePath, fileContent);
  console.log("Updated static-lms-courses.ts with course cover imageUrl.");
}

updateStaticCourses();
