const fs = require("fs")
const path = require("path")
const { cert, getApps, initializeApp } = require("firebase-admin/app")
const { getFirestore } = require("firebase-admin/firestore")

const rootDir = path.resolve(__dirname, "..")
const outputFile = path.join(rootDir, "lib", "static-lms-courses.ts")

function loadEnvFile(fileName) {
  const envPath = path.join(rootDir, fileName)
  if (!fs.existsSync(envPath)) return

  const lines = fs.readFileSync(envPath, "utf8").split(/\r?\n/)
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith("#")) continue

    const equalsIndex = trimmed.indexOf("=")
    if (equalsIndex === -1) continue

    const key = trimmed.slice(0, equalsIndex).trim()
    let value = trimmed.slice(equalsIndex + 1).trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }

    if (!process.env[key]) process.env[key] = value
  }
}

function normalizePrivateKey(privateKey) {
  let key = privateKey.replace(/^\"|\"$/g, "").replace(/\\n/g, "\n")

  if (!key.includes("\n") && key.includes("-----BEGIN PRIVATE KEY-----")) {
    const body = key
      .replace("-----BEGIN PRIVATE KEY-----", "")
      .replace("-----END PRIVATE KEY-----", "")
      .replace(/ /g, "")
    const chunks = body.match(/.{1,64}/g) || []
    key = `-----BEGIN PRIVATE KEY-----\n${chunks.join("\n")}\n-----END PRIVATE KEY-----\n`
  }

  return key
}

function initializeFirebaseAdmin() {
  loadEnvFile(".env.production")
  loadEnvFile(".env.local")
  loadEnvFile(".env")

  const projectId = process.env.FIREBASE_PROJECT_ID?.replace(/[\r\n\s]+/g, "").replace(/\\n/g, "")
  const clientEmail = process.env.FIREBASE_CLIENT_EMAIL?.replace(/[\r\n\s]+/g, "").replace(/\\n/g, "")
  const privateKey = process.env.FIREBASE_PRIVATE_KEY

  if (!projectId || !clientEmail || !privateKey) {
    throw new Error("Missing FIREBASE_PROJECT_ID, FIREBASE_CLIENT_EMAIL, or FIREBASE_PRIVATE_KEY.")
  }

  if (!getApps().length) {
    initializeApp({
      credential: cert({
        projectId,
        clientEmail,
        privateKey: normalizePrivateKey(privateKey),
      }),
    })
  }

  return getFirestore()
}

function toPlainValue(value) {
  if (value == null) return value
  if (typeof value.toDate === "function") return value.toDate().toISOString()
  if (value instanceof Date) return value.toISOString()
  if (Array.isArray(value)) return value.map(toPlainValue)
  if (typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, toPlainValue(child)]))
  }
  return value
}

function withCourseDefaults(course, docId) {
  const now = new Date().toISOString()
  return {
    id: Number(course.id ?? docId),
    slug: course.slug ?? String(docId),
    title: course.title ?? "Untitled Course",
    description: course.description ?? "",
    category: course.category ?? "General",
    level: course.level ?? "Beginner",
    format: course.format ?? "Online",
    durationHours: Number(course.durationHours ?? 0),
    priceNaira: Number(course.priceNaira ?? 0),
    subsidiaries: course.subsidiaries ?? "",
    initiative: course.initiative ?? null,
    videoUrl: course.videoUrl ?? null,
    imageUrl: course.imageUrl ?? null,
    authorId: course.authorId ?? null,
    isBriefing: course.isBriefing ?? null,
    customContent: course.customContent ?? null,
    createdAt: course.createdAt ?? now,
    updatedAt: course.updatedAt ?? now,
  }
}

function renderStaticCourseFile(courses) {
  return `import type { Course } from "@/lib/types"

export type StaticLmsCourse = Omit<Course, "createdAt" | "updatedAt"> & {
  createdAt: string | Date
  updatedAt: string | Date
}

// Generated by \`pnpm lms:export-courses\`.
// Keep this array in git so public LMS catalog/course metadata can be served
// without spending Firestore reads on every visitor, build, or page refresh.
export const STATIC_LMS_COURSE_DATA: StaticLmsCourse[] = ${JSON.stringify(courses, null, 2)}

function hydrateCourse(course: StaticLmsCourse): Course {
  return {
    ...course,
    createdAt: course.createdAt instanceof Date ? course.createdAt : new Date(course.createdAt),
    updatedAt: course.updatedAt instanceof Date ? course.updatedAt : new Date(course.updatedAt),
  }
}

export function getStaticLmsCourses(): Course[] {
  return STATIC_LMS_COURSE_DATA.map(hydrateCourse).sort((a, b) => {
    const category = a.category.localeCompare(b.category)
    return category !== 0 ? category : a.title.localeCompare(b.title)
  })
}

export function hasStaticLmsCourses(): boolean {
  return STATIC_LMS_COURSE_DATA.length > 0
}

export function getStaticLmsCourseBySlug(slug: string): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.slug === slug)
  return course ? hydrateCourse(course) : null
}

export function getStaticLmsCourseById(id: number): Course | null {
  const course = STATIC_LMS_COURSE_DATA.find((item) => item.id === id)
  return course ? hydrateCourse(course) : null
}
`
}

async function main() {
  const db = initializeFirebaseAdmin()
  const snap = await db.collection("courses").orderBy("category").orderBy("title").get()
  const courses = snap.docs.map((doc) => withCourseDefaults(toPlainValue(doc.data()), doc.id))

  fs.writeFileSync(outputFile, renderStaticCourseFile(courses), "utf8")
  console.log(`Exported ${courses.length} LMS courses to ${path.relative(rootDir, outputFile)}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
