import { initializeApp, getApps, cert } from "firebase-admin/app";
import { getFirestore } from "firebase-admin/firestore";
import fs from "fs";
import path from "path";

const serviceAccountPath = path.join(process.cwd(), "firebase-admin.json");
const serviceAccount = JSON.parse(fs.readFileSync(serviceAccountPath, "utf8"));

if (!getApps().length) {
  initializeApp({ credential: cert(serviceAccount) });
}

const db = getFirestore();

// High-quality, voluminous data to patch the drone masterclass.
const dronePatches: Record<string, any> = {
  "lesson-1-drone-fundamentals": {
    knowledgeCheck: {
      type: "matching",
      id: "kc-drone-1",
      prompt: "Match the drone aerodynamic concept to its primary characteristic.",
      pairs: [
        { left: "Lift", right: "The upward force generated by pressure differences across an airfoil." },
        { left: "Drag", right: "The aerodynamic resistance opposing the drone's forward motion." },
        { left: "Thrust", right: "The forward force produced by the propulsion system." },
        { left: "Pitch", right: "The rotational movement controlling the drone's nose up or down." }
      ],
      explanation: "Understanding these fundamental aerodynamic forces is critical for designing and operating fixed-wing and multirotor drones."
    },
    interactiveTabs: [
      {
        tabTitle: "Lift Generation",
        content: "Lift is the fundamental force that keeps a drone airborne, counteracting gravity. It is generated primarily by the wings in a fixed-wing aircraft or the rotors in a multirotor. According to Bernoulli's principle and Newton's third law of motion, the shape of an airfoil (the wing or rotor blade cross-section) forces air traveling over the top surface to accelerate, creating a region of lower pressure compared to the bottom surface. This pressure differential results in an upward force.\n\nIn multirotors, lift is directly proportional to the square of the rotor's angular velocity and the blade's pitch angle. Engineers must carefully balance lift requirements with the weight of the drone, including payloads and batteries. If the required thrust-to-weight ratio is too low, the drone will lack the agility to maneuver or recover from perturbations. High-performance racing drones, for example, often boast thrust-to-weight ratios exceeding 10:1, while heavy-lift enterprise drones may operate closer to 2:1 to prioritize efficiency and endurance."
      },
      {
        tabTitle: "Managing Drag",
        content: "Drag is the aerodynamic resistance that opposes a drone's forward motion through the air. It is categorized into two main types: parasitic drag and induced drag. Parasitic drag increases with the square of the velocity and includes form drag (caused by the drone's shape), skin friction drag (caused by surface roughness), and interference drag (caused by turbulent airflow mixing between components). To minimize parasitic drag, engineers use aerodynamic fairings, retract landing gear, and ensure smooth surface finishes.\n\nInduced drag, on the other hand, is a byproduct of lift generation. As high-pressure air from beneath the wing spills over the wingtips to the low-pressure area above, it creates wingtip vortices. These vortices induce a downward velocity to the local airflow, tilting the lift vector backward and creating a drag component. Induced drag decreases as speed increases. Fixed-wing drones often employ winglets or high-aspect-ratio wings to reduce the strength of these vortices, significantly improving cruising efficiency."
      }
    ]
  },
  "lesson-2-drone-control-systems": {
    knowledgeCheck: {
      type: "matching",
      id: "kc-drone-2",
      prompt: "Match the PID control term to its function in stabilizing a drone.",
      pairs: [
        { left: "Proportional (P)", right: "Provides a response proportional to the current error from the setpoint." },
        { left: "Integral (I)", right: "Eliminates steady-state error by accumulating past errors over time." },
        { left: "Derivative (D)", right: "Dampens the system response by predicting future error based on the rate of change." },
        { left: "Setpoint", right: "The desired target state or attitude commanded by the pilot or autopilot." }
      ],
      explanation: "A well-tuned PID controller uses all three terms (P, I, and D) to achieve rapid, stable, and accurate flight responses without dangerous oscillations."
    },
    interactiveTabs: [
      {
        tabTitle: "PID Algorithm",
        content: "The Proportional-Integral-Derivative (PID) algorithm is the industry standard for drone flight control loops. It operates by continuously calculating an error value — the difference between a desired setpoint (e.g., zero degrees of pitch) and a measured process variable (e.g., current pitch from the IMU). The algorithm applies a correction based on proportional, integral, and derivative terms. The Proportional (P) term provides a thrust correction that is directly proportional to the current error size. However, relying on 'P' alone can lead to continuous oscillation around the setpoint.\n\nTo eliminate steady-state error, the Integral (I) term accumulates past errors over time. If a drone is hovering but a constant wind pushes it slightly off course, the 'I' term builds up over time to provide the extra thrust needed to overcome the wind. Finally, the Derivative (D) term predicts future error by analyzing the rate of change. It acts as a damper, slowing down the 'P' term's aggressive correction as the drone approaches the setpoint, thereby preventing overshoot. Proper PID tuning is an iterative, complex process critical to achieving crisp, locked-in flight characteristics."
      },
      {
        tabTitle: "MPC Algorithm",
        content: "Model Predictive Control (MPC) represents a more advanced control paradigm than standard PID, often utilized in cutting-edge experimental or highly dynamic drones. Unlike PID, which reacts to current and past errors, MPC proactively plans future control actions. It uses a dynamic mathematical model of the drone's physics to predict its future state over a specific time horizon. At each time step, the algorithm solves a real-time optimization problem to find the optimal sequence of control inputs (e.g., rotor RPMs) that will minimize a cost function (such as deviation from a trajectory) while strictly adhering to physical constraints (e.g., maximum motor torque or battery current limits).\n\nWhile MPC provides superior performance — particularly in complex maneuvers or when recovering from extreme disturbances — it requires significantly more computational power. Modern flight control computers (FCCs) equipped with powerful microprocessors or FPGAs are now making real-time MPC feasible for smaller drones. This allows for aggressive trajectory tracking and safe operation near obstacles, as the controller explicitly accounts for the drone's dynamic limits before issuing commands."
      }
    ]
  },
  "advanced-drone-system-integration": {
    interactiveTabs: [
      {
        tabTitle: "Avionics Integration",
        content: "Avionics integration is the critical process of combining all electronic systems within the drone architecture to function as a cohesive unit. This includes the flight control computer (FCC), inertial measurement units (IMUs), GPS receivers, telemetry radios, and payload controllers. A primary challenge in avionics integration is managing Electromagnetic Interference (EMI). High-current power lines running to the ESCs generate powerful magnetic fields that can corrupt sensitive digital signals or interfere with the magnetometer (compass). Engineers must carefully route power and data cables separately, utilize twisted-pair wiring, and employ faraday cages or shielding tapes to isolate critical components.\n\nFurthermore, modern avionics systems rely on robust communication buses like CAN bus (Controller Area Network) or MavLink over serial connections. CAN bus provides a fault-tolerant, differential signaling network that allows various peripherals to communicate reliably even in electronically noisy environments. Ensuring that software drivers are correctly configured to handle data rates, latency, and packet loss across these buses is essential for a stable flight stack."
      },
      {
        tabTitle: "Power Distribution",
        content: "The Power Distribution Board (PDB) or power management system is the cardiovascular system of the drone. It must handle immense current spikes from multiple high-power brushless motors while simultaneously providing clean, regulated voltage to sensitive flight electronics. Enterprise drones often utilize smart batteries with integrated Battery Management Systems (BMS) that monitor individual cell voltages, temperature, and cycle counts, communicating this data to the FCC via a data bus (like SMBus or CAN).\n\nDesigning the power distribution network requires careful thermal management. ESCs and voltage regulators generate significant heat under load. If this heat is not dissipated efficiently through heatsinks or airflow, components can suffer thermal runaway, leading to catastrophic failure. Additionally, redundancy is a critical consideration for heavy-lift or passenger drones. Redundant power architectures ensure that the failure of a single battery or PDB component does not result in total power loss, allowing the drone to execute an emergency landing protocol safely."
      }
    ]
  }
};

async function main() {
  const snapshot = await db.collection("courses").where("slug", "==", "the-complete-drone-technology-masterclass").get();
  if (snapshot.empty) {
    console.error("Course not found!");
    process.exit(1);
  }

  const docRef = snapshot.docs[0].ref;
  const courseData = snapshot.docs[0].data();

  let customContent: any;
  try {
    customContent = JSON.parse(courseData.customContent);
  } catch (e) {
    console.error("Failed to parse customContent:", e);
    process.exit(1);
  }

  let updatedCount = 0;

  for (const lesson of customContent.lessons) {
    const patch = dronePatches[lesson.key];
    if (patch) {
      if (patch.knowledgeCheck) {
        lesson.knowledgeCheck = patch.knowledgeCheck;
        console.log(`✅ Patched knowledgeCheck for: ${lesson.title}`);
      }
      if (patch.interactiveTabs) {
        lesson.interactiveTabs = patch.interactiveTabs;
        console.log(`✅ Patched interactiveTabs for: ${lesson.title}`);
      }
      updatedCount++;
    } else {
        // Just in case other lessons have empty knowledgeCheck, give them a generic but valid one
        if (lesson.knowledgeCheck && (!lesson.knowledgeCheck.pairs || lesson.knowledgeCheck.pairs.length === 0)) {
            lesson.knowledgeCheck = {
                type: "matching",
                id: `kc-generic-${lesson.key}`,
                prompt: "Match the technical concept to its definition.",
                pairs: [
                    { left: "System Reliability", right: "The probability that a system will perform its required function under specified conditions." },
                    { left: "Latency", right: "The time delay between a command being issued and the system responding." },
                    { left: "Redundancy", right: "The inclusion of extra components which are not strictly necessary to functioning, in case of failure in other components." },
                    { left: "Bandwidth", right: "The maximum rate of data transfer across a given path." }
                ],
                explanation: "These foundational technical concepts apply across all advanced systems in the masterclass."
            }
            console.log(`✅ Auto-filled missing knowledgeCheck pairs for: ${lesson.title}`);
        }
    }
  }

  const updatedCustomContent = JSON.stringify(customContent);
  await docRef.update({
    customContent: updatedCustomContent,
    updatedAt: new Date()
  });

  console.log(`\n✅ Firestore updated with patched content! Modified ${updatedCount} lessons with specific patches.`);

  // Update static-lms-courses.ts
  const staticPath = path.join(process.cwd(), "lib", "static-lms-courses.ts");
  let staticContent = fs.readFileSync(staticPath, "utf8");

  const slugPattern = `"slug": "the-complete-drone-technology-masterclass"`;
  const slugIndex = staticContent.indexOf(slugPattern);
  
  if (slugIndex !== -1) {
    let courseStart = slugIndex;
    while (courseStart > 0 && staticContent[courseStart] !== '{') courseStart--;
    
    let courseEnd = courseStart;
    let braceCount = 0;
    for (let i = courseStart; i < staticContent.length; i++) {
      if (staticContent[i] === '{') braceCount++;
      if (staticContent[i] === '}') braceCount--;
      if (braceCount === 0) {
        courseEnd = i;
        break;
      }
    }
    
    const courseBlock = staticContent.substring(courseStart, courseEnd + 1);
    const oldCustomContentMatch = courseBlock.match(/"customContent":\s*"((?:[^"\\]|\\.)*)"/);
    if (oldCustomContentMatch) {
      const newBlock = courseBlock.replace(oldCustomContentMatch[0], `"customContent": ${JSON.stringify(updatedCustomContent)}`);
      staticContent = staticContent.replace(courseBlock, newBlock);
      fs.writeFileSync(staticPath, staticContent);
      console.log("✅ static-lms-courses.ts updated!");
    }
  }

  process.exit(0);
}

main().catch(console.error);
