name: On-Premise Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy .env file
        run: |
          cp ../.env .env
          cat .env >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Next.js App
        run: pnpm run build
        env:
          CI: true

      - name: Restart PM2 Process
        run: |
          pm2 reload ecosystem.config.js --env production || pm2 start ecosystem.config.js --env production
          pm2 save
